// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="shift_pattern_gen_top_shift_pattern_gen_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu19p_CIV-fsva3824-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.283500,HLS_SYN_LAT=105,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=31,HLS_SYN_LUT=178,HLS_VERSION=2022_2}" *)

module shift_pattern_gen_top (
        ap_clk,
        ap_rst,
        top_led_o,
        first_value
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
output  [2:0] top_led_o;
input  [2:0] first_value;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_done;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_idle;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_ready;
wire   [2:0] grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_tmp_o_V_out;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_tmp_o_V_out_ap_vld;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_done;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_idle;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_ready;
wire   [2:0] grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_top_led_o;
wire    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_top_led_o_ap_vld;
reg    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start_reg = 1'b0;
#0 grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start_reg = 1'b0;
end

shift_pattern_gen_top_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1 grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start),
    .ap_done(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_done),
    .ap_idle(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_idle),
    .ap_ready(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_ready),
    .first_value(first_value),
    .tmp_o_V_out(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_tmp_o_V_out),
    .tmp_o_V_out_ap_vld(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_tmp_o_V_out_ap_vld)
);

shift_pattern_gen_top_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1 grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start),
    .ap_done(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_done),
    .ap_idle(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_idle),
    .ap_ready(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_ready),
    .tmp_o_V_reload(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_tmp_o_V_out),
    .top_led_o(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_top_led_o),
    .top_led_o_ap_vld(grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_top_led_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start_reg <= 1'b1;
        end else if ((grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_ready == 1'b1)) begin
            grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start_reg <= 1'b1;
        end else if ((grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_ready == 1'b1)) begin
            grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start_reg <= 1'b0;
        end
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start = grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_ap_start_reg;

assign grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start = grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_76_1_fu_40_ap_start_reg;

assign top_led_o = grp_shift_pattern_gen_top_Pipeline_VITIS_LOOP_31_1_fu_47_top_led_o;

endmodule //shift_pattern_gen_top
